### ISSUE TITLE
Packages for Linux distributions

### ISSUE THREAD

**Issue by tobimensch** [zbabac/VCT#3]
this project appears to be useful. Thank you for it.

Could you create snaps, AppImages or FlatPacks for easy installation on Linux systems?

Also distributions like Fedora, Debian or Ubuntu will surely be willing to include packages
in their official repositories. But first you have to make them aware of your project.

**Comment by zbabac** [comment]
Thanks for your comment. I wouldn't call this an issue, since it has nothing to do with the program functioning properly. Most Linux users are comfortable with command line. However, I thought about it, but it's not so simple. Although, there is just 1 binary, VCT.exe, there must be ffmpeg, ffprobe and ffplay Linux binaries, and of course, mono for Linux installed. AppImages and FlatPak can't include all those dependencies (or they are just too big). 

In the meantime, for those that don't like to meddle with command line, I prepared 2 scripts and updated latest release.
For APT package manager (Debian, Ubuntu, etc), just download **VCT_Linux_mono_binary.zip** and **install_vct_apt.sh**, download to $HOME/Downloads and execute (provide sudo credentials):
`./install_vct_apt.sh`  or just double click it - execute in terminal!
For Fedora, Centos, etc. with YUM package manager download **VCT_Linux_mono_binary.zip** and **install_vct_yum.sh**, download to $HOME/Downloads and execute (provide sudo credentials):
`./install_vct_yum.sh`  or just double click it - execute in terminal!

After that, in `$HOME/VCT_mono/` there will be start script: **vct.sh** just copy it to the Desktop and double click, it will execute the program!

For other distros that use other package managers, please read INSTALL_README.txt and install manually.
