### ISSUE TITLE
Missing start buttons

### ISSUE THREAD

**Issue by Zsombi55** [zbabac/VCT#4]
On the conversion tab the start button is missing. It is not present even in full screen window mode. Even if I keep pressing TAB on the keyboard to switch selections, and press Enter when nothing seems selected, it still won't start. So this is unusable for conversion.
![kep](https://user-images.githubusercontent.com/47913849/200115262-d409ad61-0dfe-4c3b-8390-8c85d9de54c7.JPG)

**Comment by zbabac** [comment]
What is the OS that you're using (Windows 10, 7, 8, Linux), and what version of VCT did you install (e.g. VCT_setup_64bit.exe)?
Another question: do you use windows scaling, if yes, which rate (e.g. 125%, 150%)? I've just tested myself and found out that it has problem with 150% (partially hidden buttons) and higher (175% and 200% no buttons visible). I didn't create app to be fully DPI aware, so that may be the issue. Please check your DPI and let me know.
You're the first one to complain, so thank you for bringing this to my attention. I will correct it, but be aware that I am doing it in my free time, it may take some days.

**Comment by Zsombi55** [comment]
Windows 10, 64 bit
VCT_setup_64bit.exe

**Comment by Zsombi55** [comment]
Windows 10, 64 bit
VCT_setup_64bit.exe
The resolution is 1366x768, landscape, default scaling (100%).

**Comment by zbabac** [comment]
I made a small correction and updated the latest release. It works for resolutions 1600x1050 and up. 
But I think it will not help you, since I fixed minimum window size to 960x722. With taskbar, it will be too big for your screen. I didn't anticipate smaller displays. It will take some more time, but I will try to fix this. 
The fact is that I added features on user requests and tried to squeeze everything on this tab (in the end I have to move time range copy to Transcode tab, although it works also for Convert as well). 
I never tested on res 1366x768 thinking that it will fit, but obviously not. The whole app needs UI rewriting, but not today!
Hoping to fix soon!

**Comment by Zsombi55** [comment]
Hi! Thank you for replying :)

The way I would have solved this issue is by making the Batch List
short enough so the lowest buttons fit within the window, with it
being made dynamically auto-resizing, finally I would make the window
size adjustable like most application windows are (resize, maximize,
restore down). That way when a user makes the app. window bigger, the
Batch List size will adjust accordingly, but if the user makes it
smaller scroll bars could appear. (I know some people hate scroll
bars, but those are the simplest in my opinion.)

I'm just an amateur at programming, and haven't touched a piece of
code in a long time, but these were my first thoughts on the problem.
I hope it is of some help for the future.


Cheers!

**Comment by zbabac** [comment]
Thanks for the insight, but that was not the problem. resizing is done automatically by the framework, with use of properties, like anchor (for example for panel container). Btw. batch list can be very long, so it has scrollbars if it is larger than container in which it sits (panelBatch). You can try it yourself, I usually use batch to make videos from mobile phone smaller (sometimes hundreds of files), with option "Multiple Input Files".
Anyway, I fixed it for the lowest resolution of 1360x768 (Window can't fit on anything smaller). I also fixed some other properties and tested on a real PC with that resolution. It works and resizes properly.

Please uninstall and download the release 1.9.6.2 again (VCT_setup_64bit.exe).

**Comment by zbabac** [comment]
I renamed the latest release to 1.9.7, which features improved GUI elements, smallest working resolution 1200x800 and flat appearance (to provide the same look on Windows and Linux). With that release I will close this issue.
